"""add sentence_ir

Revision ID: 3d27fb3b8abd
Revises: 9c4a7f6a2b11
Create Date: 2026-02-28 17:51:36.297940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d27fb3b8abd'
down_revision: Union[str, Sequence[str], None] = '9c4a7f6a2b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expression', 'translation_run_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('expression', 'sentence_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expression', 'sentence_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('expression', 'translation_run_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
