"""add review_queue resolution fields

Revision ID: 478d80d7421a
Revises: 3d27fb3b8abd
Create Date: 2026-02-28 19:16:00.513036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '478d80d7421a'
down_revision: Union[str, Sequence[str], None] = '3d27fb3b8abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_uid_mapping',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('old_uid', sa.String(length=255), nullable=False),
    sa.Column('new_uid', sa.String(length=255), nullable=False),
    sa.Column('mapping_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_uid_mapping_new_uid'), 'concept_uid_mapping', ['new_uid'], unique=False)
    op.create_index(op.f('ix_concept_uid_mapping_old_uid'), 'concept_uid_mapping', ['old_uid'], unique=False)
    op.create_index('ux_concept_uid_mapping_old_new', 'concept_uid_mapping', ['old_uid', 'new_uid'], unique=True)
    op.add_column('review_queue', sa.Column('resolution', sa.Text(), nullable=True))
    op.add_column('review_queue', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('review_queue', sa.Column('dismissed_reason', sa.Text(), nullable=True))
    op.add_column('review_queue', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('review_queue', sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_queue', 'dismissed_at')
    op.drop_column('review_queue', 'resolved_at')
    op.drop_column('review_queue', 'dismissed_reason')
    op.drop_column('review_queue', 'notes')
    op.drop_column('review_queue', 'resolution')
    op.drop_index('ux_concept_uid_mapping_old_new', table_name='concept_uid_mapping')
    op.drop_index(op.f('ix_concept_uid_mapping_old_uid'), table_name='concept_uid_mapping')
    op.drop_index(op.f('ix_concept_uid_mapping_new_uid'), table_name='concept_uid_mapping')
    op.drop_table('concept_uid_mapping')
    # ### end Alembic commands ###
