"""baseline schema

Revision ID: 617257da99ce
Revises: 
Create Date: 2026-02-26 21:14:49.697206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '617257da99ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept',
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('pref_label', sa.Text(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('document',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_content_hash'), 'document', ['content_hash'], unique=False)
    op.create_table('relation_type',
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('pref_label', sa.Text(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('review_queue',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('item_type', sa.String(length=64), nullable=False),
    sa.Column('item_ref', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expression',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('subject_uid', sa.String(length=255), nullable=False),
    sa.Column('relation_uid', sa.String(length=255), nullable=False),
    sa.Column('object_uid', sa.String(length=255), nullable=True),
    sa.Column('object_literal', sa.Text(), nullable=True),
    sa.Column('qualifiers_json', sa.JSON(), nullable=True),
    sa.Column('provenance_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['relation_uid'], ['relation_type.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expression_object_uid'), 'expression', ['object_uid'], unique=False)
    op.create_index(op.f('ix_expression_relation_uid'), 'expression', ['relation_uid'], unique=False)
    op.create_index(op.f('ix_expression_subject_uid'), 'expression', ['subject_uid'], unique=False)
    op.create_table('sentence',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('sentence_index', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_start', sa.BigInteger(), nullable=True),
    sa.Column('char_end', sa.BigInteger(), nullable=True),
    sa.Column('page_no', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sentence_doc_idx', 'sentence', ['document_id', 'sentence_index'], unique=True)
    op.create_index(op.f('ix_sentence_document_id'), 'sentence', ['document_id'], unique=False)
    op.create_table('term',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('concept_uid', sa.String(length=255), nullable=False),
    sa.Column('lang', sa.String(length=16), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('label_norm', sa.Text(), nullable=False),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['concept_uid'], ['concept.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_term_concept_uid'), 'term', ['concept_uid'], unique=False)
    op.create_index(op.f('ix_term_label_norm'), 'term', ['label_norm'], unique=False)
    op.create_index('ix_term_lang_norm', 'term', ['lang', 'label_norm'], unique=False)
    op.create_index('ux_term_concept_lang_norm', 'term', ['concept_uid', 'lang', 'label_norm'], unique=True)
    op.create_table('translation_run',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('tool_version', sa.String(length=64), nullable=True),
    sa.Column('llm_provider', sa.String(length=64), nullable=True),
    sa.Column('llm_model', sa.String(length=128), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_run_document_id'), 'translation_run', ['document_id'], unique=False)
    op.create_table('advisor_call',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('translation_run_id', sa.BigInteger(), nullable=False),
    sa.Column('request_json', sa.JSON(), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('decision_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['translation_run_id'], ['translation_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisor_call_translation_run_id'), 'advisor_call', ['translation_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advisor_call_translation_run_id'), table_name='advisor_call')
    op.drop_table('advisor_call')
    op.drop_index(op.f('ix_translation_run_document_id'), table_name='translation_run')
    op.drop_table('translation_run')
    op.drop_index('ux_term_concept_lang_norm', table_name='term')
    op.drop_index('ix_term_lang_norm', table_name='term')
    op.drop_index(op.f('ix_term_label_norm'), table_name='term')
    op.drop_index(op.f('ix_term_concept_uid'), table_name='term')
    op.drop_table('term')
    op.drop_index(op.f('ix_sentence_document_id'), table_name='sentence')
    op.drop_index('ix_sentence_doc_idx', table_name='sentence')
    op.drop_table('sentence')
    op.drop_index(op.f('ix_expression_subject_uid'), table_name='expression')
    op.drop_index(op.f('ix_expression_relation_uid'), table_name='expression')
    op.drop_index(op.f('ix_expression_object_uid'), table_name='expression')
    op.drop_table('expression')
    op.drop_table('review_queue')
    op.drop_table('relation_type')
    op.drop_index(op.f('ix_document_content_hash'), table_name='document')
    op.drop_table('document')
    op.drop_table('concept')
    # ### end Alembic commands ###
